name: just_a_min
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  url_launcher: ^6.2.4
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  googleapis: ^9.0.0
  googleapis_auth: ^1.3.0
  flutter_dotenv: ^5.1.0
  http: ^0.13.5
  image_picker: ^1.0.4
  path_provider: ^2.0.14
  path: ^1.8.2  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/image1.png
    - assets/icons/icon1.png

  # CORRECTED ICON CONFIGURATION (fixed indentation)
flutter_icons:  # <-- Moved to root level
  android: true
  ios: true
  image_path: "assets/icons/icon1.png"