name: roborave_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^9.0.0
  googleapis_auth: ^1.3.0
  flutter_dotenv: ^5.1.0
  http: ^0.13.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:  # <-- Moved to root level
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/image2.png
    - assets/icons/icon1.png  # <-- Add this if your icon exists here