name: ablemate
description: A new Flutter project.

# Prevents accidental publishing to pub.dev
publish_to: 'none'

# App version and build number
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  http: ^0.13.5
  image_picker: ^1.0.4       # For picking images from gallery/camera
  path_provider: ^2.0.14     # For storing files locally
  path: ^1.8.2               # File path utilities
  cupertino_icons: ^1.0.2    # iOS-style icons
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

# Flutter-specific configurations
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Example for adding custom fonts (optional)
  # fonts:
  #   - family: YourFontFamily
  #     fonts:
  #       - asset: fonts/YourFont-Regular.ttf
  #       - asset: fonts/YourFont-Bold.ttf
  #         weight: 700

# Optional: launcher icons configuration (if using flutter_launcher_icons)
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/app_icon.png"
